spring.datasource.url=jdbc:mysql://localhost:3306/realtimechat
spring.datasource.username=root
spring.datasource.password=Aryanf143
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.websocket.enabled=true

server.port=8080